### PR TITLE
rm ext-bcmath dependency

### PR DESCRIPTION
**Pull request by terrafrost**

### CODE REVIEW

**Comment by ramsey** [comment]
A few quick things…

1. Please remove 5.3 from the `.travis.yml` file
2. Update the README so that it no longer says the bcmath extension is required

Thanks!

**Comment by terrafrost** [comment]
Done!

I wonder if it'd be a good idea to add 7.2 and 7.2 to `.travis.yml`?

**Comment by ramsey** [comment]
Please do!

**Comment by ramsey** [comment]
Actually, it looks like PHP 7 has some errors, and we might need to modify tests so that the bcmath polyfill you’re using isn’t ignored because Travis CI already has the bcmath extension installed. I can help with some of this, if needed. Let me know.

**Comment by terrafrost** [comment]
It wouldn't surprise me if the PHP 7 errors were just due to changes PHP made in the way BCMath behaves. The changes I'm aware of in newer PHP versions are as follows:

PHP 7.2.0:
- **bcmod**: dividend and divisor are no longer truncated to integer, so now the behavior of bcmod() follows fmod() rather than the % operator. [source](https://www.php.net/manual/en/function.bcmod.php#refsect1-function.bcmod-changelog)
- **bcmod**: The scale parameter was added. [source](https://www.php.net/manual/en/function.bcmod.php#refsect1-function.bcmod-changelog)
- **bcpow**: bcpow() now returns numbers with the requested scale. Formerly, the returned numbers may have omitted trailing decimal zeroes. [source](https://www.php.net/manual/en/function.bcpow.php#refsect1-function.bcpow-changelog)

PHP 7.3.0:
- **bcscale**: bcscale() can now be used to get the current scale factor; when used as setter, it now returns the old scale value. Formerly, scale was mandatory, and bcscale() always returned TRUE. [source](https://www.php.net/manual/en/function.bcscale.php#refsect1-function.bcscale-changelog)
- **bcmul**: fix inconsistent truncation [source](https://bugs.php.net/66364)

I'll see what I can figure out w.r.t. to them.

One thing that would be cool would be is the ability to have two instances of each Travis CI VM - one with bcmath and one without. I'm not sure how to do that tho. In an attempt to figure out, however, I posted on SO:

https://stackoverflow.com/q/56318348/569976

**Comment by terrafrost** [comment]
So yah it looks like PHP changed how `bccomp` works:

https://3v4l.org/JNjar

Here's the bug report that resulted in that change:

http://bugs.php.net/46781 ([cache](https://webcache.googleusercontent.com/search?q=cache:sjvKCcX980sJ:https://bugs.php.net/46781+&cd=1&hl=en&ct=clnk&gl=us))

The changelog entry:

https://www.php.net/ChangeLog-7.php#7.0.24

Not sure how this should best be handled.

**Comment by terrafrost** [comment]
I've made some updates to this.

- the unit tests are now run with and without bcmath. see .travis.yml for details.
- i've removed the `ini_set` / `ini_get` stuff as they only work if the bcmath extension is installed. see bcmath_compat's README.md for details.
- i'm emulating the behavior of `bccomp` prior to http://bugs.php.net/46781 to make the `testNegativeZero` test work on PHP 7.0+. bcmath_compat uses the post http://bugs.php.net/46781 behavior (as evidenced by the fact that it "provides" "ext-bcmath": "7.3.5") so this is also needed for the unit tests to work when bcmath isn't available.
- i removed hhvm from Travis since it was failing in a way that makes it seem like it's more of an issue with Composer than anything idk: https://travis-ci.org/ramsey/moontoast-math/jobs/548932145

**Comment by terrafrost** [comment]
This now has 100% unit test coverage.

Is there anything else that I need to do get this merged in? If there are no plans to merge it in then maybe close this PR?

**Comment by ramsey** [comment]
Thanks! I’ll review soon and let you know. Great work!

**Comment by ramsey** [comment]
Thank you for contributing! 🎉

Sorry it's taken me so long to merge this.

**Pull request merged**
